// Copyright (c) Meta Platforms, Inc. and affiliates.
//
// This software may be used and distributed according to the terms of the
// GNU General Public License version 2.
//
// scx_atlas - AI Training Latency-Aware Scheduler (prototype).
//
// This crate exposes the BPF interface/skeleton bindings, the scheduler's
// configuration options, and the `init_open_skel!` macro that populates the
// BPF-side const-volatile config structs (p2dq-style, principle #8).

pub mod bpf_intf;
pub mod bpf_skel;

use clap::Parser;
use lazy_static::lazy_static;
use scx_utils::Topology;

lazy_static! {
    /// Host topology, built once and shared across the userspace component.
    pub static ref TOPO: Topology =
        Topology::new().expect("Failed to build host topology");
}

/// Tunable scheduler options. Kept intentionally small (principle #7); per-class
/// tuning and GPU/IRQ knobs are added in later phases.
#[derive(Debug, Clone, Parser)]
pub struct SchedulerOpts {
    /// Default time slice in microseconds for non-latency classes.
    #[clap(long, default_value = "5000")]
    pub slice_us_default: u64,

    /// Time slice in microseconds for the latency (GPU) class.
    #[clap(long, default_value = "1000")]
    pub slice_us_latency: u64,

    /// Minimum time-slice floor in microseconds (cf. CFS min_granularity).
    #[clap(long, default_value = "500")]
    pub min_slice_us: u64,

    /// Max sleeper vtime credit in microseconds (cf. EEVDF lag / CFS sleeper
    /// fairness): bounds how far behind a waking task's vtime can be.
    #[clap(long, default_value = "5000")]
    pub slice_lag_us: u64,

    /// Keep per-CPU kthreads dispatched locally for latency.
    #[clap(long, default_value = "true", action = clap::ArgAction::Set)]
    pub kthreads_local: bool,

    /// Let LATENCY tasks preempt lower-class tasks when no idle CPU is free.
    #[clap(long, default_value = "true", action = clap::ArgAction::Set)]
    pub preempt_latency: bool,

    /// Bias placement toward a task's preferred NUMA node (its mempolicy).
    #[clap(long, default_value = "true", action = clap::ArgAction::Set)]
    pub mempolicy_aware: bool,

    /// Let LATENCY (GPU) tasks ignore sched_yield() so they stay on-CPU during
    /// busy-poll loops (lower latency for CUDA/NCCL-style spinning).
    #[clap(long, default_value = "true", action = clap::ArgAction::Set)]
    pub yield_ignore: bool,

    /// Minimum time (us) since a task's last NUMA migration before it's eligible
    /// to be stolen cross-NUMA (avoids ping-ponging tasks across nodes).
    #[clap(long, default_value = "1000")]
    pub xnuma_mig_min_us: u64,

    /// Regex matched against a task's cgroup path (relative to the cgroup root,
    /// e.g. "^workload.slice" for a prefix, "foo$" for a suffix, or any regex for
    /// autogenerated names) selecting the TRAINING class. Empty disables.
    /// Resolved to cgroup ids in userspace.
    #[clap(long, default_value = "")]
    pub training_cgroup: String,

    /// Regex selecting the PREP class (see --training-cgroup).
    #[clap(long, default_value = "")]
    pub prep_cgroup: String,
}

/// Populate the BPF `rodata` config structs from the parsed options and host
/// topology, before the skeleton is loaded.
#[macro_export]
macro_rules! init_open_skel {
    ($open_skel:expr, $topo:expr, $opts:expr) => {{
        let open_skel = &mut *$open_skel;
        let opts: &$crate::SchedulerOpts = $opts;
        let topo: &scx_utils::Topology = &$topo;

        let rodata = open_skel
            .maps
            .rodata_data
            .as_mut()
            .expect("rodata is not memory mapped");

        rodata.topo_config.nr_cpus = *scx_utils::NR_CPU_IDS as u32;
        rodata.topo_config.nr_llcs = topo.all_llcs.len() as u32;
        rodata.topo_config.nr_nodes = topo.nodes.len() as u32;
        rodata.topo_config.smt_enabled = std::mem::MaybeUninit::new(topo.smt_enabled);

        // Per-CPU -> LLC / NUMA-node maps consumed by the BPF dispatch path.
        let max_cpus = rodata.cpu_llc_ids.len();
        for cpu in topo.all_cpus.values() {
            if cpu.id >= max_cpus {
                anyhow::bail!(
                    "CPU id {} exceeds MAX_CPUS ({}); bump MAX_CPUS in intf.h",
                    cpu.id,
                    max_cpus
                );
            }
            rodata.cpu_llc_ids[cpu.id] = cpu.llc_id as u32;
            rodata.cpu_node_ids[cpu.id] = cpu.node_id as u32;
        }

        rodata.atlas_config.slice_us_default = opts.slice_us_default;
        rodata.atlas_config.slice_us_latency = opts.slice_us_latency;
        rodata.atlas_config.min_slice_us = opts.min_slice_us;
        rodata.atlas_config.slice_lag_us = opts.slice_lag_us;
        rodata.atlas_config.kthreads_local = std::mem::MaybeUninit::new(opts.kthreads_local);
        rodata.atlas_config.mempolicy_aware = std::mem::MaybeUninit::new(opts.mempolicy_aware);
        rodata.atlas_config.xnuma_mig_min_us = opts.xnuma_mig_min_us;
        rodata.atlas_config.preempt_latency = std::mem::MaybeUninit::new(opts.preempt_latency);
        rodata.atlas_config.yield_ignore = std::mem::MaybeUninit::new(opts.yield_ignore);
        // cgroup classification (training_cgroup/prep_cgroup regexes) is resolved
        // in userspace into the cgroup_class map; nothing to set in rodata.

        anyhow::Ok(())
    }};
}
